name: credit_capture
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  any_loading: ^0.0.1+2
  auto_route: ^5.0.4
  country_picker: ^2.0.2
  cupertino_icons: ^1.0.5
  dotted_border: ^2.0.0+3
  easy_localization: ^3.0.1
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_hooks: ^0.18.5+1
  freezed_annotation: ^2.2.0 
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  injectable: ^2.1.0
  loggy: ^2.0.1  

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: 2.3.3
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  hive_generator: ^2.0.0
  injectable_generator: ^2.1.3
  very_good_analysis: ^3.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/